"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ShoppingListPanel } from "@/modules/shopping-list/panel";
import { PricingPanel } from "@/modules/pricing/panel";
import { PurchasePanel } from "@/modules/purchases/panel";
import { RecommendationPanel } from "@/modules/recommendation/panel";
import { PRODUCT_UNITS, PRODUCT_UNIT_LABELS, type HouseholdProduct, type InventoryStatus, type ProductUnit, type ShoppingProfile } from "./types";

const statusLabel: Record<InventoryStatus, string> = { in_stock: "Em casa", low: "Acabando", out: "Acabou" };
const shortUnit: Record<ProductUnit, string> = { kg: "kg", g: "g", l: "L", ml: "ml", unit: "un.", roll: "rolo", package: "emb." };
type AppView = "today" | "list" | "stock" | "markets" | "house";
const navItems: { id: AppView; icon: string; label: string }[] = [
  { id: "today", icon: "⌂", label: "Hoje" },
  { id: "list", icon: "✓", label: "Lista" },
  { id: "stock", icon: "▦", label: "Estoque" },
  { id: "markets", icon: "◇", label: "Mercados" },
  { id: "house", icon: "⌘", label: "Casa" },
];

export function HouseholdDashboard() {
  const supabase = useMemo(() => createClient(), []);
  const [view, setView] = useState<AppView>("today");
  const [householdId, setHouseholdId] = useState<string | null>(null);
  const [houseName, setHouseName] = useState("Minha Casa"); const [city, setCity] = useState(""); const [displayName, setDisplayName] = useState("");
  const [shoppingProfile, setShoppingProfile] = useState<ShoppingProfile>("balanced"); const [products, setProducts] = useState<HouseholdProduct[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);

  const load = useCallback(async () => { setLoading(true); const { data: profile, error: profileError } = await supabase.from("user_profiles").select("household_id,city,display_name,shopping_profile").single(); if (profileError || !profile?.household_id) { setMessage("Não foi possível carregar seu perfil."); setLoading(false); return; } setHouseholdId(profile.household_id); setCity(profile.city ?? ""); setDisplayName(profile.display_name ?? ""); setShoppingProfile(profile.shopping_profile as ShoppingProfile); const [{ data: house }, { data: productRows, error: productsError }] = await Promise.all([supabase.from("households").select("name,city").eq("id", profile.household_id).single(), supabase.from("products").select("id,name,brand,package_quantity,package_unit,locked,inventory_items(id,registered_quantity,estimated_quantity,unit,status)").eq("household_id", profile.household_id).order("name")]); if (house) { setHouseName(house.name); if (!profile.city) setCity(house.city ?? ""); } if (productsError) setMessage("Não foi possível carregar os produtos."); else setProducts((productRows ?? []) as HouseholdProduct[]); setLoading(false); }, [supabase]);
  useEffect(() => { void load(); }, [load]);

  async function saveHouse(event: FormEvent) { event.preventDefault(); if (!householdId) return; const cleanCity=city.trim(); const {error:houseError}=await supabase.from("households").update({name:houseName.trim()||"Minha Casa",city:cleanCity||null}).eq("id",householdId); const {error:profileError}=await supabase.from("user_profiles").update({display_name:displayName.trim()||null,city:cleanCity||null,shopping_profile:shoppingProfile}).eq("household_id",householdId); setMessage(houseError||profileError?"Não foi possível salvar seus dados.":"Casa e preferências salvas."); }
  async function addProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(!householdId)return; const el=event.currentTarget, form=new FormData(el), name=String(form.get("name")??"").trim(), brand=String(form.get("brand")??"").trim(), unit=String(form.get("unit")??"unit") as ProductUnit, packageQuantity=Number(form.get("packageQuantity")??1), stock=Number(form.get("stock")??0); if(!name||packageQuantity<=0||stock<0){setMessage("Revise nome e quantidades do produto.");return;} const {data:product,error}=await supabase.from("products").insert({household_id:householdId,name,brand:brand||null,package_quantity:packageQuantity,package_unit:unit}).select("id,name,brand,package_quantity,package_unit,locked").single(); if(error||!product){setMessage("Não foi possível cadastrar o produto.");return;} const {data:inventory,error:inventoryError}=await supabase.from("inventory_items").insert({household_id:householdId,product_id:product.id,registered_quantity:stock,estimated_quantity:stock,unit:"package"}).select("id,registered_quantity,estimated_quantity,unit,status").single(); if(inventoryError||!inventory){await supabase.from("products").delete().eq("id",product.id);setMessage("Não foi possível criar o estoque do produto.");return;} setProducts(c=>[...c,{...product,inventory_items:[inventory]} as HouseholdProduct].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"))); el.reset();setMessage("Produto adicionado à Minha Casa."); }
  async function changeStock(product:HouseholdProduct,delta:number){const inventory=product.inventory_items[0];if(!inventory)return;const next=Math.max(0,Number(inventory.registered_quantity)+delta),nextStatus:InventoryStatus=next<=0?"out":inventory.status==="out"?"in_stock":inventory.status;setProducts(c=>c.map(i=>i.id===product.id?{...i,inventory_items:[{...inventory,registered_quantity:next,estimated_quantity:next,status:nextStatus}]}:i));const{error}=await supabase.from("inventory_items").update({registered_quantity:next,estimated_quantity:next,unit:"package"}).eq("id",inventory.id);if(error){setProducts(c=>c.map(i=>i.id===product.id?product:i));setMessage("Não foi possível alterar o estoque.");return;}setMessage("Estoque atualizado.");}
  async function setStatus(product:HouseholdProduct,status:InventoryStatus){const inventory=product.inventory_items[0];if(!inventory)return;const nextInventory=status==="out"?{...inventory,status,registered_quantity:0,estimated_quantity:0}:{...inventory,status};setProducts(c=>c.map(i=>i.id===product.id?{...i,inventory_items:[nextInventory]}:i));const patch=status==="out"?{status,registered_quantity:0,estimated_quantity:0}:{status};const{error}=await supabase.from("inventory_items").update(patch).eq("id",inventory.id);if(error){setProducts(c=>c.map(i=>i.id===product.id?product:i));setMessage("Não foi possível alterar o status.");return;}setMessage("Status atualizado.");}
  async function removeProduct(product:HouseholdProduct){if(!window.confirm(`Remover ${product.name} da sua casa?`))return;setProducts(c=>c.filter(i=>i.id!==product.id));const{error}=await supabase.from("products").delete().eq("id",product.id);if(error){setProducts(c=>[...c,product].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")));setMessage("Não foi possível remover o produto.");return;}setMessage("Produto removido.");}
  async function signOut(){await supabase.auth.signOut();window.location.href="/login";}
  if(loading)return <main className="app-shell"><div className="loading-state"><span className="brand-mark">L</span><p>Preparando sua casa…</p></div></main>;

  const lowCount=products.filter(p=>p.inventory_items[0]?.status==="low").length; const outCount=products.filter(p=>p.inventory_items[0]?.status==="out").length;
  const stockContent=<><section className="card inventory"><div className="section-title"><div><div className="card-kicker">MINHA DESPENSA</div><h2>Estoque</h2><p>{products.length} produto(s) cadastrados</p></div></div>{products.length===0?<div className="empty">Sua casa ainda está vazia. Cadastre o primeiro produto na aba Casa.</div>:<div className="product-list">{products.map(product=>{const inv=product.inventory_items[0],count=Number(inv?.registered_quantity??0),packageQty=Number(product.package_quantity??0),total=packageQty>0?count*packageQty:0;return <article className="product" key={product.id}><div className="product-main"><strong>{product.name}</strong><span>{product.brand||"Sem marca"} · {product.package_quantity??"—"} {product.package_unit?shortUnit[product.package_unit]:""} por embalagem</span>{total>0&&product.package_unit&&<small>Total: {total} {shortUnit[product.package_unit]}</small>}</div><div className="stock"><button onClick={()=>changeStock(product,-1)} aria-label={`Diminuir ${product.name}`}>−</button><b>{count} {count===1?"embalagem":"embalagens"}</b><button onClick={()=>changeStock(product,1)} aria-label={`Aumentar ${product.name}`}>+</button></div><select className={`status ${inv?.status??"out"}`} value={inv?.status??"out"} onChange={e=>setStatus(product,e.target.value as InventoryStatus)} aria-label={`Status de ${product.name}`}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="danger-link" onClick={()=>removeProduct(product)}>Remover</button></article>})}</div>}</section></>;
  const houseContent=<><section className="grid two"><form className="card" onSubmit={saveHouse}><div className="card-kicker">PREFERÊNCIAS</div><h2>Dados da casa</h2><label>Seu nome<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Como quer ser chamado"/></label><label>Nome da casa<input value={houseName} onChange={e=>setHouseName(e.target.value)}/></label><label>Cidade<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: Goiânia"/></label><label>Perfil de compra<select value={shoppingProfile} onChange={e=>setShoppingProfile(e.target.value as ShoppingProfile)}><option value="economic">Econômico</option><option value="balanced">Equilibrado</option><option value="practical">Prático</option></select></label><button className="button" type="submit">Salvar alterações</button></form><form className="card" onSubmit={addProduct}><div className="card-kicker">CATÁLOGO DA CASA</div><h2>Novo produto</h2><label>Produto<input name="name" required placeholder="Ex.: Arroz"/></label><label>Marca<input name="brand" placeholder="Opcional"/></label><div className="row"><label>Tamanho da embalagem<input name="packageQuantity" type="number" min="0.001" step="0.001" defaultValue="1" required/></label><label>Unidade<select name="unit" defaultValue="unit">{PRODUCT_UNITS.map(u=><option key={u} value={u}>{PRODUCT_UNIT_LABELS[u]}</option>)}</select></label></div><label>Embalagens em casa<input name="stock" type="number" min="0" step="1" defaultValue="0" required/></label><p className="field-help">Ex.: 3 pacotes de 5 kg = 15 kg em casa.</p><button className="button" type="submit">Adicionar produto</button></form></section><button className="button secondary logout-button" onClick={signOut}>Sair da conta</button></>;

  const heading = {
    today:["VISÃO GERAL",`Olá${displayName?`, ${displayName.split(" ")[0]}`:""}!`,"O que merece sua atenção agora."],
    list:["PRÓXIMA COMPRA","Lista de compras","Monte a lista, acompanhe o orçamento e compre sem perder o foco."],
    stock:["DESPENSA","Estoque","Veja o que tem em casa e o que está acabando."],
    markets:["ECONOMIA","Mercados","Compare filiais com transparência sobre cobertura e validade."],
    house:["PREFERÊNCIAS","Casa","Dados da casa, perfil de compra e catálogo de produtos."],
  }[view];

  return <main className="app-shell redesigned"><header className="app-header"><button className="brand-button" onClick={()=>setView("today")}><span className="brand-mark">L</span><span><b>Lista Inteligente</b><small>{houseName}</small></span></button><button className="avatar-button" onClick={()=>setView("house")} aria-label="Abrir configurações da casa">{(displayName||"U").slice(0,1).toUpperCase()}</button></header>{message&&<div className="notice floating-notice" role="status">{message}</div>}
    <div className="view-heading"><div><span className="eyebrow">{heading[0]}</span><h1>{heading[1]}</h1><p>{heading[2]}</p></div></div>
    {view==="today"&&<><section className="overview-grid"><button className="overview-card" onClick={()=>setView("list")}><span>Sua próxima compra</span><strong>Revisar lista</strong><small>Planeje itens e orçamento</small></button><button className="overview-card attention" onClick={()=>setView("stock")}><span>Atenção no estoque</span><strong>{outCount} acabaram</strong><small>{lowCount} estão acabando</small></button><button className="overview-card" onClick={()=>setView("markets")}><span>Onde comprar</span><strong>Comparar mercados</strong><small>Use apenas preços válidos</small></button></section>{householdId&&<RecommendationPanel householdId={householdId} products={products} shoppingProfile={shoppingProfile}/>}</>}
    {view==="list"&&householdId&&<><ShoppingListPanel householdId={householdId} products={products}/><PurchasePanel householdId={householdId}/></>}
    {view==="stock"&&stockContent}
    {view==="markets"&&householdId&&<PricingPanel householdId={householdId} products={products} city={city}/>} 
    {view==="house"&&houseContent}
    <nav className="bottom-nav" aria-label="Navegação principal">{navItems.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)} aria-current={view===item.id?"page":undefined}><span>{item.icon}</span><small>{item.label}</small></button>)}</nav>
  </main>;
}
